apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-micro-s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: mini-crm/auth
---
apiVersion: v1
kind: Service
metadata:
  name: auth-micro-s
spec:
  selector:
    app: auth-service
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000

